<?php

$routing = [
    '/' => 'index',
    '/index' => 'index',
    '/logowanie' => 'logowanie',
    '/wylogowanie' => 'wylogowanie',
    '/rejestracja' => 'rejestracja',
    '/success' => 'success',
    '/dramat' => 'dramat',
    '/dramhist' => 'dramhist',
    '/fantasy' => 'fantasy',
    '/horror' => 'horror',
    '/upload' => 'upload',
    '/galeria' => 'galeria',
    '/info' => 'info',
    '/kategorie' => 'kategorie',
    '/komedia' => 'komedia',
    '/kryminal' => 'kryminal',
    '/scifi' => 'scifi',
    '/bb' => 'bb',
    '/bcs' => 'bcs',
    '/lucyfer' => 'lucyfer',
    '/sherlock' => 'sherlock',
    '/st' => 'st',
    '/wiking' => 'wiking',
    '/seriale' => 'seriale',
    '/nav' => 'nav',
    '/head' => 'head',
    '/footer' => 'footer',
];
